/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 7, 2010
 * Project: Project 4a
 * File: Book.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4a;

import java.io.Serializable;

public abstract class Book implements Serializable, BookInterface, SpecificGenreBookInterface {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -5141037058874469067L;
	
	private String 	author,
					title,
					isbn;
	
	protected Book(String author, String title, String isbn) {
		this.author = author;
		this.title = title;
		this.isbn = isbn;
	}
	
	protected Book() {}
	
	/**
	 * Abstract methods subclass must implement
	 */
	public abstract String getGenre();
	public abstract String getAttribute();
	public abstract void setAttribute(String attribute);
	
	/**
	 * Built-in getters common to all types of books
	 */
	public final String getAuthor() {return author;}
	public final String getTitle() {return title;}
	public final String getISBN() {return isbn;}
	
	@Override
	public String toString() {return(getAuthor()+":"+getTitle()+":"+getISBN());}
	
	/**
	 * Built-in setters common to all types of books
	 */
	public final void setAuthor(String author) { this.author = author; }
	public final void setTitle(String title) { this.title = title; }
	public final void setISBN(String isbn) { this.isbn = isbn; }
}
