/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 7, 2010
 * Project: Project 4a
 * File: Borrower.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4a;

import java.io.Serializable;

import java.util.Calendar;

public class Borrower implements BorrowerInterface, Comparable<Borrower>, Serializable {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 6325278335992640076L;

	private String 		clientName;
	
	private Calendar 	borrowDate, // Borrow date will also be the ID
						dueDate;
	
	public Borrower(String c, int days) {
		clientName = c;
		borrowDate = Calendar.getInstance();
		dueDate = (Calendar) this.borrowDate.clone();
		dueDate.add(Calendar.DAY_OF_YEAR, days);  // People can check out books for i days.
	}
	
	public String getClientName() {
		return clientName;
	}

	public Calendar getBorrowDate() {
		return borrowDate;
	}

	public Calendar getDueDate() {
		return dueDate;
	}
	
	public long getID() {
		return dueDate.getTimeInMillis();
	}
	
	public long getLongDueDate() {
		return dueDate.getTimeInMillis();
	}
	
	public long getLongBorrowDate() {
		return borrowDate.getTimeInMillis();
	}
	
	public int compareTo(Borrower b) {
		return dueDate.compareTo(b.getDueDate());
	}
	
	public String toString() {
		String s = clientName+":"
					+String.valueOf(getLongBorrowDate())+":"
					+String.valueOf(getLongDueDate());
		return s;
	}
}
