/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 7, 2010
 * Project: Project 4a
 * File: ChildrenBook.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4a;

/**
 * @author jsmith
 *
 */
public class ChildrenBook extends Book {

	
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -2791124913105188897L;
	
	private static final String genre = "Children";
	private String attribute;

	public ChildrenBook(String author, String title, String isbn, String age) {
		super(author, title, isbn);
		attribute = age;
	}
	
	public ChildrenBook() {}

	@Override
	public String getGenre() {return genre;}

	@Override
	public String getAttribute() {return attribute;}

	/* (non-Javadoc)
	 * @see project4a.SpecificGenreBookInterface#setAttribute(java.lang.String)
	 */
	@Override
	public void setAttribute(String age) {
		attribute = age;
	}
	
	@Override
	public String toString() {return(getAuthor()+":"+getTitle()+":"+getISBN())+":"+getGenre()+":"+getAttribute();}
}
