/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 7, 2010
 * Project: Project 4a
 * File: GenericBook.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4a;

/**
 * @author jsmith
 *
 */
public class GenericBook extends Book {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -579986416699768280L;
	
	private static final String genre = "Literature";
	private String attribute;

	public GenericBook(String author, String title, String isbn, String fictionType) {
		super(author, title, isbn);
		attribute = fictionType;
	}
	
	public GenericBook() {}

	@Override
	public String getGenre() {return genre;}

	@Override
	public String getAttribute() {return attribute;}

	/* (non-Javadoc)
	 * @see project4a.SpecificGenreBookInterface#setAttribute(java.lang.String)
	 */
	@Override
	public void setAttribute(String fictionType) {
		attribute = fictionType;
	}
	
	@Override
	public String toString() {return(getAuthor()+":"+getTitle()+":"+getISBN())+":"+getGenre()+":"+getAttribute();}
}
