/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 8, 2010
 * Project: Project 4b
 * File: Book.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4b;

import java.io.Serializable;

public class Book implements Serializable, BookInterface {
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -5141037058874469067L;
	
	private String 	author,
					title,
					isbn;
	
	public Book(String author, String title, String isbn) {
		this.author = author;
		this.title = title;
		this.isbn = isbn;
	}
	
	public Book() {}

	/**
	 * Built-in getters common to all types of books
	 */
	public String getAuthor() {return author;}
	public String getTitle() {return title;}
	public String getISBN() {return isbn;}
	
	@Override
	public String toString() {return(getAuthor()+":"+getTitle()+":"+getISBN());}
	
	/**
	 * Built-in setters common to all types of books
	 */
	public void setAuthor(String author) { this.author = author; }
	public void setTitle(String title) { this.title = title; }
	public void setISBN(String isbn) { this.isbn = isbn; }
}
