/**
 * Author: Justin Smith
 * Course: CMSC335.6380
 * Date: Aug 8, 2010
 * Project: Project 4b
 * File: ChildrenBook.java
 * Development Environment:  Apple Mac OS X 10.6.4
 *                           Eclipse 3.6 / Java 1.6.0_20
 */
package project4b;

import java.io.Serializable;

/**
 * @author jsmith
 *
 */
public class ChildrenBook implements Serializable, SpecificGenreBookInterface {

	
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -2791124913105188897L;
	
	private static final String genre = "Children";
	private String attribute;
	
	private Book book;

	public ChildrenBook(String author, String title, String isbn, String age) {
		book = new Book(author, title, isbn);
		attribute = age;
	}
	
	public ChildrenBook() {
		book = new Book();
	}
	
	public String getAuthor() { return book.getAuthor(); }
	
	public String getTitle() { return book.getTitle(); }
	
	public String getISBN() { return book.getISBN(); }

	public String getGenre() {return genre;}

	public String getAttribute() {return attribute;}
	
	/**
	 * Returns colon delimted string representation of Book data.
	 */
	@Override
	public String toString() {
		return(book.toString()+":"
				  +getGenre()+":"
				  +getAttribute());
	}
	

	/* (non-Javadoc)
	 * @see project4b.BookInterface#setAuthor(java.lang.String)
	 */
	@Override
	public void setAuthor(String author) {book.setAuthor(author);}

	/* (non-Javadoc)
	 * @see project4b.BookInterface#setTitle(java.lang.String)
	 */
	@Override
	public void setTitle(String title) {book.setTitle(title);}

	/* (non-Javadoc)
	 * @see project4b.BookInterface#setISBN(java.lang.String)
	 */
	@Override
	public void setISBN(String isbn) {book.setISBN(isbn);}
	
	@Override
	public void setAttribute(String topic) { attribute = topic; }
}
