//**********************************************************************
//        File: account.idl
// Description:
//     The purpose of this file is to define the account class interface.  
//      Author: Mike Tarquinio
// Environment: CORBA IDL
//
//**********************************************************************

// IDL for Account
module AccountModule {

   interface Account
      {
   	  
      // get the current balance for the user.                          
      long getbalance();

      // add money to the account.
      void deposit(in long amount);

      // withdrawl money from the account.
      void withdrawl(in long amount);

      // get the social security number for the account.                          
      string getsocialsecuritynumber();   
      };
};     
   
  
