/* 
**  Author: Justin Smith
**  Course: CMIS 420.7980
**  Date:  05/10/14
**  Final Project
*/


-- DROP EVERYTHING BEFORE CREATING
DROP TABLE SALES;
DROP TABLE AGENT;
DROP TABLE PERIOD;
DROP TABLE TERRITORY;
DROP TABLE POLICY;


-- Create Tables
CREATE TABLE AGENT 
(
  AGENTCODE NUMBER NOT NULL 
, AGENTID NUMBER NOT NULL 
, AGENTNAME VARCHAR2(20) NOT NULL 
, CONSTRAINT AGENT_PK PRIMARY KEY 
  (
    AGENTCODE 
  )
  ENABLE 
);

CREATE TABLE PERIOD 
(
  PERIODCODE NUMBER NOT NULL 
, YEAR NUMBER NOT NULL 
, QUARTER NUMBER NOT NULL 
, MONTH NUMBER NOT NULL 
, CONSTRAINT PERIOD_PK PRIMARY KEY 
  (
    PERIODCODE 
  )
  ENABLE 
);

CREATE TABLE TERRITORY 
(
  TERRITORYCODE NUMBER NOT NULL 
, ZIPCODE VARCHAR2(5) NOT NULL 
, CONSTRAINT TERRITORY_PK PRIMARY KEY 
  (
    TERRITORYCODE 
  )
  ENABLE 
);

CREATE TABLE POLICY 
(
  POLICYCODE NUMBER NOT NULL 
, AGENTCODE NUMBER NOT NULL 
, EFFECTIVEDATE DATE NOT NULL 
, POLICYTYPE VARCHAR2(20) NOT NULL 
, INITCOMMISSION NUMBER NOT NULL 
, COMMISSION NUMBER NOT NULL 
, FACEVALUE NUMBER NOT NULL 
, CONSTRAINT POLICY_PK PRIMARY KEY 
  (
    POLICYCODE 
  )
  ENABLE 
);

CREATE TABLE SALES 
(
  POLICYCODE NUMBER NOT NULL 
, PERIODCODE NUMBER NOT NULL 
, TERRITORYCODE NUMBER NOT NULL 
, AGENTCODE NUMBER NOT NULL 
, NUMPOLICIES NUMBER NOT NULL 
, FACEVALUETOTAL NUMBER NOT NULL 
, NUMINFORCE NUMBER NOT NULL 
, TOTALCOMMISSION NUMBER NOT NULL 
, CONSTRAINT SALES_PK PRIMARY KEY 
  (
    POLICYCODE 
  , PERIODCODE 
  , TERRITORYCODE 
  , AGENTCODE 
  )
  ENABLE 
);

ALTER TABLE SALES
ADD CONSTRAINT SALES_AGENT_FK1 FOREIGN KEY
(
  AGENTCODE 
)
REFERENCES AGENT
(
  AGENTCODE 
)
ENABLE;

ALTER TABLE SALES
ADD CONSTRAINT SALES_PERIOD_FK1 FOREIGN KEY
(
  PERIODCODE 
)
REFERENCES PERIOD
(
  PERIODCODE 
)
ENABLE;

ALTER TABLE SALES
ADD CONSTRAINT SALES_POLICY_FK1 FOREIGN KEY
(
  POLICYCODE 
)
REFERENCES POLICY
(
  POLICYCODE 
)
ENABLE;

ALTER TABLE SALES
ADD CONSTRAINT SALES_TERRITORY_FK1 FOREIGN KEY
(
  TERRITORYCODE 
)
REFERENCES TERRITORY
(
  TERRITORYCODE 
)
ENABLE;


-- Crate Test Data

