// -- BankService.idl
// -- Justin Smith
// -- CMIS445.6980
// -- Final Project
// -- 03/09/14
// -- CORBA IDL
// -- Build Settings - idlj -oldImplBase -Fall

// -- ORB Service
module BankService {

  enum AccountType { checking, saving };

  struct Address {
    string street;
    string city;
    string state;
    long zip;
  };

  struct AccountHistory {
    sequence<string> history;
  };

  struct Account {
    long accountID;
    string lastName;
    string firstName;
    string SSN;
    DateTime DOB;
    Address address;
    string phoneNumber;
    string emailAddress;
    long savingBalance;
    long checkingBalance;
    AccountHistory transactions;
  };

  interface TellerService {
    Account getAccount (in long accountID);

    // -- Boolean values indicate sucessful transaction
    boolean deposit (in AccountType accountType, in long amount, in long accountID);
    boolean withdraw (in AccountType accountType, in long amount, in long accountID);
    boolean transfer (in AccountType accountType, in long amount,
                      in long accountID, in long tooAccountID);

    boolean addAccount (in Account account, in long managerID, in long managerPin);
  };

  interface AuthTeller {
    // -- Basic "security", boolean will indicate sucess/failure, client program
    // -- will "respect" boolean = false.
    boolean login (in long tellerID, in long tellerPin);
    boolean logout (in long tellerID);
  };

};
