// -- BankService.idl
// -- Justin Smith
// -- CMIS445.6980
// -- Final Project
// -- 03/09/14
// -- CORBA IDL
// -- Build Settings - idlj -Fall

// -- ORB Service

module BankService {
  struct Customer {
    long accountID;
    string lastName;
    string firstName;
    string SSN;
    string pin;
    double checkingBalance;
    double SavingsBalance;
  };

//  interface Customer {
//    string getLastName();
//    string getFirstName();
//    string getSSN();
//    string getPin();
//
//    double getCheckingBalance();
//    double getSavingsBalance();
//
//    void setLastName(in string lastName);
//    void setFirstName(in string firstName);
//    void setSSN(in string SSN);
//    void setPin(in string pin);
//  };

  interface TellerService {
    boolean login (in string userID, in string PIN);

    double deposit (in long accountID, in string accountType, in long amount);
    double withdraw (in long accountID, in string accountType, in long amount);
    double cashCheck (in long accountID, in long checkNumber, in long amount);
    double transfer (in long accountID, in string accountType, in long toAccountID, in long amount);

    long createAccount (in BankService::Customer newCustomer);

    oneway void shtudown();
  };
};
