DROP  table Person_T CASCADE CONSTRAINTS;

DROP  TABLE Physician_T CASCADE CONSTRAINTS;

DROP TABLE Assessment_T CASCADE CONSTRAINTS;

DROP  TABLE Patient_T CASCADE CONSTRAINTS;

DROP  TABLE Employee_T CASCADE CONSTRAINTS;

DROP  TABLE Volunteer_T CASCADE CONSTRAINTS;

DROP TABLE Facility_T CASCADE CONSTRAINTS;

DROP TABLE Vendor_T CASCADE CONSTRAINTS;

DROP TABLE Item_T CASCADE CONSTRAINTS;

DROP TABLE Diagnosis_T CASCADE CONSTRAINTS;

DROP TABLE Outpatient_T CASCADE CONSTRAINTS;

DROP TABLE Visit_T CASCADE CONSTRAINTS;

DROP TABLE Nurse_T CASCADE CONSTRAINTS;

DROP TABLE RN_T CASCADE CONSTRAINTS;

DROP TABLE LPN_T CASCADE CONSTRAINTS;

DROP TABLE WorkUnit_T CASCADE CONSTRAINTS;

DROP TABLE CareCenter_T CASCADE CONSTRAINTS;



dROP  TABLE Room_T CASCADE CONSTRAINTS;

dROP  TABLE Bed_T CASCADE CONSTRAINTS;

dROP TABLE Resident_T CASCADE CONSTRAINTS;

dROP TABLE PhysicianDx_T CASCADE CONSTRAINTS;

dROP TABLE CCAssignment_T CASCADE CONSTRAINTS;

dROP TABLE FieldCertification_T CASCADE CONSTRAINTS;

DROP TABLE staff_T CASCADE CONSTRAINTS;

DROP TABLE Technician_T CASCADE CONSTRAINTS;

DROP TABLE TechnicianSkill_T CASCADE CONSTRAINTS;

DROP TABLE DiagnosticUnit_T CASCADE CONSTRAINTS;

DROP TABLE Treatment_T CASCADE CONSTRAINTS;

DROP TABLE Order_T CASCADE CONSTRAINTS;

DROP TABLE TreatmentOrder_T CASCADE CONSTRAINTS;

DROP TABLE ItemConsumption_T CASCADE CONSTRAINTS;

DROP TABLE ItemBilling_T CASCADE CONSTRAINTS;

DROP TABLE Inventory_T CASCADE CONSTRAINTS;

DROP TABLE Schedule_T CASCADE CONSTRAINTS;


DROP TABLE VolMVCHService CASCADE CONSTRAINTS;

DROP TABLE VolRefInfo CASCADE CONSTRAINTS;

DROP TABLE VolExperience_T CASCADE CONSTRAINTS;

DROP TABLE VolLanguage_T CASCADE CONSTRAINTS;

DROP TABLE VolSkill_T CASCADE CONSTRAINTS;

DROP TABLE VolInterest_T CASCADE CONSTRAINTS;

DROP TABLE VolAvailability_T CASCADE CONSTRAINTS;

DROP TABLE VolServHistory_T CASCADE CONSTRAINTS;






